include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    unused_import: error
    unused_local_variable: warning
    dead_code: warning
  exclude:
    - build/**
    - ios/**
    - windows/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - use_super_parameters

formatter:
  page_width: 100
